### ISSUE TITLE
in pass and fail, dur003 and ipd006 include p with no region

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/imsc-hrm-tests#3]
https://github.com/w3c/imsc-hrm-tests/blob/2393baeb431a624e09f7b23cf326de5e1c48da74/fail/dur003-fail.ttml#L14-L16

https://github.com/w3c/imsc-hrm-tests/blob/2393baeb431a624e09f7b23cf326de5e1c48da74/fail/ipd006-fail.ttml#L14-L16

https://github.com/w3c/imsc-hrm-tests/blob/2393baeb431a624e09f7b23cf326de5e1c48da74/pass/dur003-pass.ttml#L14-L16

https://github.com/w3c/imsc-hrm-tests/blob/2393baeb431a624e09f7b23cf326de5e1c48da74/pass/ipd006-pass.ttml#L14-L16

In all cases the document defines a region, so there is no default region, but there is a `<p>` that is not associated with any region. It's not clear why it is present and what effect it is intended to have in the IMSC-HRM algorithm.

Suggest deleting this `<p>` or associating it with a region, or if it's intended to have an effect, adding an XML comment explaining its unusual presence.

Is it there to produce an empty ISD, perhaps?

**Comment by palemieux** [comment]
As far as I can tell these elements were either copy-paste mistakes.
